# Generated by Django 5.2.11 on 2026-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('01', 'Confirmé'), ('02', 'Annulé')], default='01', max_length=10),
        ),
    ]
